FROM node:20-slim

RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma/

RUN npx prisma generate

COPY . .

RUN npm install -g nodemon

EXPOSE 3000

CMD ["nodemon", "--legacy-watch", "src/server.js"]